apiVersion: apps/v1
kind: Deployment
metadata:
  name: term-check
  labels:
    project: term-check
    role: app-server
    team: bots
spec:
  replicas: 1
  selector:
    matchLabels:
      project: term-check
      role: app-server
  template:
    metadata:
      labels:
        project: term-check
        role: app-server
        team: bots
      annotations:
        secret/WEBHOOK_SECRET_KEY: webhook_secret_key
        secret/PRIVATE_KEY: private_key

    spec:
      containers:
      - name: term-check
        image: gcr.io/docker-images-180022/apps/term-check:latest
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
        ports:
          - name: http
            containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: term-check
  labels:
    project: term-check
    role: app-server
    team: bots
spec:
  selector:
    project: term-check
    role: app-server
  ports:
    - name: http
      port: 8080
      targetPort: http
