name: CI Tests

on:
  pull_request:
  push:
    branches: master

jobs:
  run-tests:
    name: Run Tests
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
      GOPATH: ${{ github.workspace }}/gopath
    steps:
    - uses: zendesk/checkout@v2
      with:
        fetch-depth: 3
    - uses: zendesk/setup-go@v2
      with:
        go-version: 1.14.15
    - uses: zendesk/cache@v2
      with:
        path: ${{ github.workspace }}/gopath
        key: ${{ runner.os }}-go-${{ hashFiles('go.sum') }}
    - run: go mod download
    - run: make

  lint:
    name: Lint
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
      GOPATH: ${{ github.workspace }}/gopath
    steps:
    - uses: zendesk/checkout@v2
      with:
        fetch-depth: 3
    - name: golangci-lint
      uses: zendesk/golangci-lint-action@v2
