name: CI Tests

on:
  pull_request:
  push:
    branches: master

jobs:
  run-tests:
    name: Run Tests
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
      GOPATH: ${{ github.workspace }}/gopath
    steps:
    - uses: zendesk/setup-go@v2
      with:
        go-version: 1.14.15
    - uses: zendesk/cache@v2
      with:
        path: ${{ github.workspace }}/gopath
        key: ${{ runner.os }}-go-${{ hashFiles('go.sum') }}
    - run: curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | bash -s -- -b $GOPATH/bin v1.19.1
    - run: go mod download
    - run: golangci-lint run
    - run: make
